name: Deploy to DigitalOcean
on:
  push:
    branches:
      - main
      - mobile-responsive
      
jobs:
  push_to_registry:
    name: Build and push Docker image to DigitalOcean Container Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY }}/gen-sp:latest
          dockerfile: Dockerfile
